### PR TITLE
types/index.ts: dont pass abi path for cairo 1.0 contract calls

### LINKED ISSUE #347: AbiFormatError with Cairo1
I cloned:

https://github.com/0xSpaceShard/starknet-hardhat-example

And updated the cairo1 contract view to:
```rust
#[view]
fn get_balance(lama: felt252) -> felt252 {
     balance::read()
}
```

When running a simple test:
```ts
    before(async function () {
        account = await getPredeployedOZAccount();
        contractFactory = await starknet.getContractFactory("cairo1");
        await account.declare(contractFactory, { maxFee: 9e18 });
        contract = await account.deploy(contractFactory, { initial_balance });
    });
    it("should invoke", async () => {
        await account.invoke(contract, "increase_balance", {
            amount1: 20,
            amount2: 5
        });
        console.log(account.address);
        const resp = await contract.call("get_balance", { lama: 12 });
        expect(resp.response).to.be.eq(42);
    });
```

I'm running into: 
```shell
     StarknetPluginError: Could not perform call on get_balance.
Error: AbiFormatError: :1:5: Unexpected token Token('COLON', ':'). Expected one of: "*", ".", end of input.
core::felt252
    ^

Make sure to `invoke` and `estimateFee` through account, and `call` directly through contract.
```

### PR DESCRIPTION
**Pull request by cfal**
## Usage related changes

passing a cairo 1.0 abi to `starknet call` invocations result in a parser error as it's not supported, eg

```
Error: ParserError: :1:5: Unexpected token Token('COLON', ':'). Expected one of: "*", ".", end of input.
core::felt252
```

omit the abi parameter for cairo 1.0 abi's.

- Closes #347 

## Checklist:

-   [x] Formatted the code
-   [x] No linter errors + tried to avoid introducing linter warnings
-   [x] Performed a self-review of the code
-   [x] Rebased to the last commit of the target branch (or merged it into my branch)
-   [ ] Documented the changes
-   [ ] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.ts`)
-   [x] Linked issues which this PR resolves
-   [ ] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/0xSpaceShard/starknet-hardhat-example):
    -   < EXAMPLE_REPO_PR_URL > 
    -   [ ] Modified `test.sh` to use my example repo branch
    -   [ ] Restored `test.sh` to to use the original branch (after the example repo PR has been merged)
-   [ ] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)

### CODE REVIEW

File: src/types/index.ts [hunk 1]
```diff
@@ -512,10 +512,16 @@ export class StarknetContract {
         }
 
         const adaptedInput = this.adaptInput(functionName, args);
+
+        // omit cairo 1.0 ABIs as it's not supported by the cairo-lang parser.
+        const abi =
+            this.abiPath && !fs.readFileSync(this.abiPath, "utf8").includes("core::")
+                ? this.abiPath
+                : undefined;
```
Comment (FabijanC) [inline src/types/index.ts:520]: `InteractWrapperOptions` should be edited to have `abi` as an optional property (`?`). Also, shouldn't then `--abi` be optional passed in starknet-wrapper?
